name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy checks
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test

      - name: Build WASM
        run: cargo build --release --target wasm32-unknown-unknown